# Generated by Django 5.0 on 2023-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='articulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
