# Generated by Django 5.0 on 2023-12-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_disponibilidad_alter_producto_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categorias_producto',
        ),
    ]
